#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Bencode
Version  : 1.501
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/A/AR/ARISTOTLE/Bencode-1.501.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AR/ARISTOTLE/Bencode-1.501.tar.gz
Summary  : 'BitTorrent serialisation format'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Bencode-license = %{version}-%{release}
Requires: perl(Algorithm::Diff)
Requires: perl(Exporter::Tidy)
BuildRequires : buildreq-cpan
BuildRequires : perl(Algorithm::Diff)
BuildRequires : perl(Exporter::Tidy)
BuildRequires : perl(Test::Differences)
BuildRequires : perl(Text::Diff)

%description
Bencode
This module implements the BitTorrent *bencode* serialisation format, as
described in <http://www.bittorrent.org/beps/bep_0003.html#bencoding>.

%package dev
Summary: dev components for the perl-Bencode package.
Group: Development
Provides: perl-Bencode-devel = %{version}-%{release}
Requires: perl-Bencode = %{version}-%{release}

%description dev
dev components for the perl-Bencode package.


%package license
Summary: license components for the perl-Bencode package.
Group: Default

%description license
license components for the perl-Bencode package.


%prep
%setup -q -n Bencode-1.501

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Bencode
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-Bencode/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/Bencode.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Bencode.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Bencode/LICENSE
